### ISSUE TITLE
npm update

### ISSUE THREAD

**Issue by AlloMehdi** [agomezmoron/docker-gulp-angular#3]
Hello,

I used your image in a production context but I just noticed that you do : "
if [ -f "$NPM_FILE" ]
  then
  npm install
  npm update
fi
"

in the entrypoint file.

Isn't it a problem to execute npm update ? I don't want any not tested updates on dependencies.

Thank you.

**Comment by agomezmoron** [comment]
Hi @AlloMehdi,

the best option to avoid that is configuring the package.json properly with ~ and removing ^ symbols :)

Thanks!
